In [1]:
import pandas as pd

In [2]:
# table related calculation

In [3]:
# Series : series is a single column table that is of 1D

# DataFrame : Dataframe is a multi-column table that is considered 2D

In [4]:
# =========================================== Series ==================================================

In [5]:
# data = pd.Series([10,20,30,40])
data = pd.Series([10,20,30,40], index =["rohit","manas","ninad","raj"])

In [6]:
 # we can access elements in series using indexing. 

# data
data["rohit"]

np.int64(10)

In [7]:
data.ndim

1

In [8]:
# =========================================== DataFrame ==================================================

In [9]:
# DataFrame

diction = {"Name" : ["rohit","manas","ninad","raj"], "Salary" : [10000,20000,30000,40000]}

In [10]:
# data = pd.DataFrame(diction ,index=[101,102,103,104])
data = pd.DataFrame(diction)

In [11]:
data

    Name  Salary
0  rohit   10000
1  manas   20000
2  ninad   30000
3    raj   40000

In [12]:
# create data frame

diction = {"Name" : ["rohit","manas","ninad","raj"], "Salary" : [10000,20000,30000,40000], "Performance":[4,7,2,6]}

In [13]:
newdata=pd.DataFrame(diction, index=[101,102,103,104])
newdata

      Name  Salary  Performance
101  rohit   10000            4
102  manas   20000            7
103  ninad   30000            2
104    raj   40000            6

In [14]:
# =========================================== iloc ==================================================

In [15]:
# iloc = iloc is indexing based locator through which we can access a particular set of values.


newdata.iloc[1,0]

'manas'

In [16]:
# newdata.iloc[0:3,0:]
newdata.iloc[0:3,0:2]

      Name  Salary
101  rohit   10000
102  manas   20000
103  ninad   30000

In [17]:
# =========================================== loc ==================================================

In [18]:
# loc : loc is labled based indexing and in loc end value is not exclusive

In [19]:
newdata.loc[101:102,"Name":"Performance":2]
# newdata.loc[101:102,"Name":"Performance"]

      Name  Performance
101  rohit            4
102  manas            7