In [1]:
import pandas as pd

In [2]:
# table related calculation

In [3]:
# Series : series is a single column table that is of 1D

# DataFrame : Dataframe is a multi-column table that is considered 2D

In [4]:
# =========================================== Series ==================================================

In [5]:
# data = pd.Series([10,20,30,40])
data = pd.Series([10,20,30,40], index =["rohit","manas","ninad","raj"])

In [6]:
 # we can access elements in series using indexing. 

# data
data["rohit"]

np.int64(10)

In [7]:
data.ndim

1

In [8]:
# =========================================== DataFrame ==================================================

In [9]:
# DataFrame

diction = {"Name" : ["rohit","manas","ninad","raj"], "Salary" : [10000,20000,30000,40000]}

In [10]:
# data = pd.DataFrame(diction ,index=[101,102,103,104])
data = pd.DataFrame(diction)

In [11]:
data

    Name  Salary
0  rohit   10000
1  manas   20000
2  ninad   30000
3    raj   40000

In [12]:
# create data frame

diction = {"Name" : ["rohit","manas","ninad","raj"], "Salary" : [10000,20000,30000,40000], "Performance":[4,7,2,6]}

In [13]:
newdata=pd.DataFrame(diction, index=[101,102,103,104])
newdata

      Name  Salary  Performance
101  rohit   10000            4
102  manas   20000            7
103  ninad   30000            2
104    raj   40000            6

In [14]:
# =========================================== iloc ==================================================

In [15]:
# iloc = iloc is indexing based locator through which we can access a particular set of values.


newdata.iloc[1,0]

'manas'

In [16]:
# newdata.iloc[0:3,0:]
newdata.iloc[0:3,0:2]

      Name  Salary
101  rohit   10000
102  manas   20000
103  ninad   30000

In [17]:
# =========================================== loc ==================================================

In [20]:
# loc : loc is labled based indexing and in loc end value is not exclusive

In [21]:
newdata.loc[101:102,"Name":"Performance":2]
# newdata.loc[101:102,"Name":"Performance"]

      Name  Performance
101  rohit            4
102  manas            7

In [22]:
# ===========================  practice using sample superstore dataframe  =================================

In [24]:
mydata = pd.read_csv(r"/workspaces/ml/panda/sample_-_superstore (1).csv",encoding="latin-1")

In [28]:
mydata[mydata["City"] == "Henderson"]

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
538,539,CA-2015-134894,07-12-2015,11-12-2015,Standard Class,DK-12985,Darren Koutras,Consumer,United States,Henderson,...,42420,South,OFF-AP-10001271,Office Supplies,Appliances,Eureka The Boss Cordless Rechargeable Stick Vac,152.940,3,0.0,41.2938
539,540,CA-2015-134894,07-12-2015,11-12-2015,Standard Class,DK-12985,Darren Koutras,Consumer,United States,Henderson,...,42420,South,FUR-CH-10002647,Furniture,Chairs,"Situations Contoured Folding Chairs, 4/Set",283.920,4,0.0,70.9800
996,997,CA-2015-162537,28-10-2015,03-11-2015,Standard Class,RD-19585,Rob Dowd,Consumer,United States,Henderson,...,42420,South,OFF-EN-10003862,Office Supplies,Envelopes,Laser & Ink Jet Business Envelopes,10.670,1,0.0,4.9082
997,998,CA-2015-162537,28-10-2015,03-11-2015,Standard Class,RD-19585,Rob Dowd,Consumer,United States,Henderson,...,42420,South,OFF-ST-10004258,Office Supplies,Storage,Portable Personal File Box,36.630,3,0.0,9.8901
998,999,CA-2015-162537,28-10-2015,03-11-2015,Standard Class,RD-19585,Rob Dowd,Consumer,United States,Henderson,...,42420,South,FUR-FU-10002885,Furniture,Furnishings,Magna Visual Magnetic Picture Hangers,24.100,5,0.0,9.1580
999,1000,CA-2015-162537,28-10-2015,03-11-2015,Standard Class,RD-19585,Rob Dowd,Consumer,United States,Henderson,...,42420,South,FUR-FU-10001918,Furniture,Furnishings,C-Line Cubicle Keepers Polyproplyene Holder Wi...,33.110,7,0.0,12.9129
1866,1867,CA-2017-118857,15-04-2017,18-04-2017,First Class,AH-10075,Adam Hart,Corporate,United States,Henderson,...,89015,West,FUR-FU-10004460,Furniture,Furnishings,"Howard Miller 12"" Round Wall Clock",196.450,5,0.0,70.7220
2321,2322,CA-2015-109470,31-12-2015,03-01-2016,Second Class,KC-16255,Karen Carlisle,Corporate,United States,Henderson,...,42420,South,OFF-BI-10004492,Office Supplies,Binders,Tuf-Vin Binders,94.740,3,0.0,44.5278
2322,2323,CA-2015-109470,31-12-2015,03-01-2016,Second Class,KC-16255,Karen Carlisle,Corporate,United States,Henderson,...,42420,South,OFF-BI-10001072,Office Supplies,Binders,"GBC Clear Cover, 8-1/2 x 11, unpunched, 25 cov...",60.640,4,0.0,27.8944
2323,2324,CA-2015-109470,31-12-2015,03-01-2016,Second Class,KC-16255,Karen Carlisle,Corporate,United States,Henderson,...,42420,South,OFF-BI-10003707,Office Supplies,Binders,Aluminum Screw Posts,76.300,5,0.0,38.1500
2324,2325,CA-2015-109470,31-12-2015,03-01-2016,Second Class,KC-16255,Karen Carlisle,Corporate,United States,Henderson,...,42420,South,OFF-BI-10000977,Office Supplies,Binders,Ibico Plastic Spiral Binding Combs,364.800,12,0.0,167.8080
2551,2552,CA-2017-101042,19-11-2017,23-11-2017,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Henderson,...,42420,South,FUR-FU-10004665,Furniture,Furnishings,"3M Polarizing Task Lamp with Clamp Arm, Light ...",821.880,6,0.0,213.6888
2552,2553,CA-2017-101042,19-11-2017,23-11-2017,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Henderson,...,42420,South,OFF-BI-10000088,Office Supplies,Binders,GBC Imprintable Covers,21.960,2,0.0,10.7604
3088,3089,US-2017-159205,31-03-2017,02-04-2017,Second Class,DB-12910,Daniel Byrd,Home Office,United States,Henderson,...,42420,South,FUR-FU-10001591,Furniture,Furnishings,Advantus Panel Wall Certificate Holder - 8.5x11,61.000,5,0.0,25.6200
3089,3090,US-2017-159205,31-03-2017,02-04-2017,Second Class,DB-12910,Daniel Byrd,Home Office,United States,Henderson,...,42420,South,TEC-PH-10000526,Technology,Phones,Vtech CS6719,671.930,7,0.0,188.1404
3537,3538,CA-2014-158771,09-05-2014,09-05-2014,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,42420,South,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,83.250,3,0.0,14.9850
3538,3539,CA-2014-158771,09-05-2014,09-05-2014,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,42420,South,OFF-LA-10001641,Office Supplies,Labels,Avery 518,9.450,3,0.0,4.5360
3539,3540,CA-2014-158771,09-05-2014,09-05-2014,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,42420,South,OFF-LA-10003121,Office Supplies,Labels,Avery 506,20.650,5,0.0,9.4990
3540,3541,CA-2014-158771,09-05-2014,09-05-2014,Same Day,SB-20290,Sean Braxton,Corporate,United States,Henderson,...,42420,South,OFF-PA-10002689,Office Supplies,Paper,Weyerhaeuser First Choice Laser/Copy Paper (20...,45.360,7,0.0,21.7728
4378,4379,CA-2015-140830,30-11-2015,02-12-2015,Second Class,PS-18970,Paul Stevenson,Home Office,United States,Henderson,...,42420,South,OFF-EN-10000461,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Recycled Envelopes",17.480,2,0.0,8.2156
4379,4380,CA-2015-140830,30-11-2015,02-12-2015,Second Class,PS-18970,Paul Stevenson,Home Office,United States,Henderson,...,42420,South,OFF-EN-10002831,Office Supplies,Envelopes,"Tyvek Top-Opening Peel & Seel Envelopes, Gray",71.880,2,0.0,32.3460
4430,4431,CA-2016-168893,03-11-2016,08-11-2016,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,OFF-FA-10002280,Office Supplies,Fasteners,Advantus Plastic Paper Clips,20.000,4,0.0,9.6000
4431,4432,CA-2016-168893,03-11-2016,08-11-2016,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,OFF-AR-10001770,Office Supplies,Art,Economy #2 Pencils,7.980,3,0.0,2.0748
4432,4433,CA-2016-168893,03-11-2016,08-11-2016,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,FUR-FU-10002885,Furniture,Furnishings,Magna Visual Magnetic Picture Hangers,24.100,5,0.0,9.1580
4433,4434,CA-2016-168893,03-11-2016,08-11-2016,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,OFF-AR-10003772,Office Supplies,Art,Boston 16750 Black Compact Battery Pencil Shar...,8.750,1,0.0,2.6250
4434,4435,CA-2016-168893,03-11-2016,08-11-2016,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,FUR-TA-10003392,Furniture,Tables,Global Adaptabilities Conference Tables,842.940,3,0.0,160.1586
4840,4841,CA-2017-154123,20-11-2017,25-11-2017,Standard Class,SC-20050,Sample Company A,Home Office,United States,Henderson,...,42420,South,FUR-FU-10000629,Furniture,Furnishings,9-3/4 Diameter Round Wall Clock,27.580,2,0.0,11.5836
4879,4880,CA-2017-143567,02-11-2017,05-11-2017,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,OFF-EN-10004846,Office Supplies,Envelopes,Letter or Legal Size Expandable Poly String Ti...,5.320,2,0.0,2.6068
4880,4881,CA-2017-143567,02-11-2017,05-11-2017,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",975.920,4,0.0,292.7760
4881,4882,CA-2017-143567,02-11-2017,05-11-2017,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,TEC-AC-10004145,Technology,Accessories,Logitech diNovo Edge Keyboard,2249.910,9,0.0,517.4793
4882,4883,CA-2017-143567,02-11-2017,05-11-2017,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,OFF-ST-10001580,Office Supplies,Storage,Super Decoflex Portable Personal File,59.920,4,0.0,16.7776
7090,7091,CA-2015-119480,09-01-2015,13-01-2015,Standard Class,CC-12685,Craig Carroll,Consumer,United States,Henderson,...,42420,South,OFF-PA-10000474,Office Supplies,Paper,Easy-staple paper,106.320,3,0.0,49.9704
7091,7092,CA-2015-119480,09-01-2015,13-01-2015,Standard Class,CC-12685,Craig Carroll,Consumer,United States,Henderson,...,42420,South,OFF-AP-10001205,Office Supplies,Appliances,Belkin 5 Outlet SurgeMaster Power Centers,163.440,3,0.0,45.7632
7092,7093,CA-2015-119480,09-01-2015,13-01-2015,Standard Class,CC-12685,Craig Carroll,Consumer,United States,Henderson,...,42420,South,OFF-AR-10004691,Office Supplies,Art,Boston 1730 StandUp Electric Pencil Sharpener,42.760,2,0.0,11.1176
7093,7094,CA-2015-119480,09-01-2015,13-01-2015,Standard Class,CC-12685,Craig Carroll,Consumer,United States,Henderson,...,42420,South,OFF-PA-10004996,Office Supplies,Paper,"Speediset Carbonless Redi-Letter 7"" x 8 1/2""",51.550,5,0.0,24.2285
7114,7115,US-2016-102239,05-05-2016,06-05-2016,First Class,LW-16990,Lindsay Williams,Corporate,United States,Henderson,...,89015,West,FUR-TA-10003392,Furniture,Tables,Global Adaptabilities Conference Tables,1685.880,6,0.0,320.3172
7115,7116,US-2016-102239,05-05-2016,06-05-2016,First Class,LW-16990,Lindsay Williams,Corporate,United States,Henderson,...,89015,West,OFF-BI-10001890,Office Supplies,Binders,Avery Poly Binder Pockets,5.728,2,0.2,2.0048
7474,7475,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
7475,7476,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,609.980,2,0.0,274.4910
7476,7477,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796
7477,7478,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,TEC-PH-10004977,Technology,Phones,GE 30524EE4,391.980,2,0.0,113.6742
7478,7479,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,TEC-PH-10004539,Technology,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,755.960,4,0.0,204.1092
7479,7480,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-FA-10001883,Office Supplies,Fasteners,"Alliance Super-Size Bands, Assorted Sizes",31.120,4,0.0,0.3112
7480,7481,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-PA-10000955,Office Supplies,Paper,Southworth 25% Cotton Granite Paper & Envelopes,6.540,1,0.0,3.0084
8639,8640,CA-2014-129819,13-12-2014,15-12-2014,Second Class,KC-16675,Kimberly Carter,Corporate,United States,Henderson,...,42420,South,OFF-BI-10004970,Office Supplies,Binders,"ACCOHIDE 3-Ring Binder, Blue, 1""",12.390,3,0.0,5.8233
9074,9075,CA-2014-136336,21-04-2014,26-04-2014,Standard Class,DB-13555,Dorothy Badders,Corporate,United States,Henderson,...,42420,South,OFF-ST-10002574,Office Supplies,Storage,"SAFCO Commercial Wire Shelving, Black",828.840,6,0.0,0.0000
9078,9079,CA-2016-108105,16-02-2016,23-02-2016,Standard Class,GW-14605,Giulietta Weimer,Consumer,United States,Henderson,...,42420,South,FUR-FU-10003773,Furniture,Furnishings,Eldon Cleatmat Plus Chair Mats for High Pile C...,318.080,4,0.0,34.9888
9079,9080,CA-2016-108105,16-02-2016,23-02-2016,Standard Class,GW-14605,Giulietta Weimer,Consumer,United States,Henderson,...,42420,South,OFF-BI-10002412,Office Supplies,Binders,Wilson Jones Snap Scratch Pad Binder Tool fo...,5.800,1,0.0,2.6100
9273,9274,CA-2017-146983,02-09-2017,06-09-2017,Standard Class,AH-10210,Alan Hwang,Consumer,United States,Henderson,...,42420,South,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,1577.940,3,0.0,757.4112

In [32]:
mydata[(mydata["City"] == "Henderson") & (mydata["Sales"] >= 200)]

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
539,540,CA-2015-134894,07-12-2015,11-12-2015,Standard Class,DK-12985,Darren Koutras,Consumer,United States,Henderson,...,42420,South,FUR-CH-10002647,Furniture,Chairs,"Situations Contoured Folding Chairs, 4/Set",283.92,4,0.0,70.9800
2324,2325,CA-2015-109470,31-12-2015,03-01-2016,Second Class,KC-16255,Karen Carlisle,Corporate,United States,Henderson,...,42420,South,OFF-BI-10000977,Office Supplies,Binders,Ibico Plastic Spiral Binding Combs,364.80,12,0.0,167.8080
2551,2552,CA-2017-101042,19-11-2017,23-11-2017,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Henderson,...,42420,South,FUR-FU-10004665,Furniture,Furnishings,"3M Polarizing Task Lamp with Clamp Arm, Light ...",821.88,6,0.0,213.6888
3089,3090,US-2017-159205,31-03-2017,02-04-2017,Second Class,DB-12910,Daniel Byrd,Home Office,United States,Henderson,...,42420,South,TEC-PH-10000526,Technology,Phones,Vtech CS6719,671.93,7,0.0,188.1404
4434,4435,CA-2016-168893,03-11-2016,08-11-2016,Second Class,AP-10915,Arthur Prichep,Consumer,United States,Henderson,...,42420,South,FUR-TA-10003392,Furniture,Tables,Global Adaptabilities Conference Tables,842.94,3,0.0,160.1586
4880,4881,CA-2017-143567,02-11-2017,05-11-2017,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",975.92,4,0.0,292.7760
4881,4882,CA-2017-143567,02-11-2017,05-11-2017,Second Class,TB-21175,Thomas Boland,Corporate,United States,Henderson,...,42420,South,TEC-AC-10004145,Technology,Accessories,Logitech diNovo Edge Keyboard,2249.91,9,0.0,517.4793
7114,7115,US-2016-102239,05-05-2016,06-05-2016,First Class,LW-16990,Lindsay Williams,Corporate,United States,Henderson,...,89015,West,FUR-TA-10003392,Furniture,Tables,Global Adaptabilities Conference Tables,1685.88,6,0.0,320.3172
7474,7475,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.82,9,0.0,746.4078
7475,7476,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,609.98,2,0.0,274.4910
7477,7478,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,TEC-PH-10004977,Technology,Phones,GE 30524EE4,391.98,2,0.0,113.6742
7478,7479,CA-2014-167199,06-01-2014,10-01-2014,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,TEC-PH-10004539,Technology,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,755.96,4,0.0,204.1092
9074,9075,CA-2014-136336,21-04-2014,26-04-2014,Standard Class,DB-13555,Dorothy Badders,Corporate,United States,Henderson,...,42420,South,OFF-ST-10002574,Office Supplies,Storage,"SAFCO Commercial Wire Shelving, Black",828.84,6,0.0,0.0000
9078,9079,CA-2016-108105,16-02-2016,23-02-2016,Standard Class,GW-14605,Giulietta Weimer,Consumer,United States,Henderson,...,42420,South,FUR-FU-10003773,Furniture,Furnishings,Eldon Cleatmat Plus Chair Mats for High Pile C...,318.08,4,0.0,34.9888
9273,9274,CA-2017-146983,02-09-2017,06-09-2017,Standard Class,AH-10210,Alan Hwang,Consumer,United States,Henderson,...,42420,South,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,1577.94,3,0.0,757.4112

In [34]:
mydata[(mydata["City"] == "Henderson") | (mydata["Sales"] >= 200)]

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
7,8,CA-2014-115812,09-06-2014,14-06-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
10,11,CA-2014-115812,09-06-2014,14-06-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9976,9977,US-2016-103674,06-12-2016,10-12-2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.5840,2,0.20,31.1980
9979,9980,US-2016-103674,06-12-2016,10-12-2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152
9988,9989,CA-2017-163629,17-11-2017,21-11-2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [36]:
mydata[~(mydata['City'] == "Henderson") & (mydata["Sales"] >= 200)]

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
7,8,CA-2014-115812,09-06-2014,14-06-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
10,11,CA-2014-115812,09-06-2014,14-06-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
11,12,CA-2014-115812,09-06-2014,14-06-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,4,0.20,68.3568
13,14,CA-2016-161389,05-12-2016,10-12-2016,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,3,0.20,132.5922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9976,9977,US-2016-103674,06-12-2016,10-12-2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.5840,2,0.20,31.1980
9979,9980,US-2016-103674,06-12-2016,10-12-2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152
9988,9989,CA-2017-163629,17-11-2017,21-11-2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
mydata.head() # it shows first 5 rows by default
# data.head(6)

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [40]:
mydata.tail() # it shows last 5 rows by default
# data.tail(6)

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480