In [45]:
import pandas as pd

In [46]:
# table related calculation

In [47]:
# Series : series is a single column table that is of 1D

# DataFrame : Dataframe is a multi-column table that is considered 2D

In [48]:
# data = pd.Series([10,20,30,40])
data = pd.Series([10,20,30,40], index =["rohit","manas","ninad","raj"])

In [49]:
# data
data["rohit"]

np.int64(10)

In [50]:
data.ndim

1

In [51]:
# DataFrame

diction = {"Name" : ["rohit","manas","ninad","raj"], "Salary" : [10000,20000,30000,40000]}

In [52]:
# data = pd.DataFrame(diction ,index=[101,102,103,104])
data = pd.DataFrame(diction)

In [54]:
data

    Name  Salary
0  rohit   10000
1  manas   20000
2  ninad   30000
3    raj   40000

In [56]:
# create data frame

diction = {"Name" : ["rohit","manas","ninad","raj"], "Salary" : [10000,20000,30000,40000], "Performance":[4,7,2,6]}

In [61]:
newdata=pd.DataFrame(diction, index=[101,102,103,104])
newdata

      Name  Salary  Performance
101  rohit   10000            4
102  manas   20000            7
103  ninad   30000            2
104    raj   40000            6

In [64]:
# iloc = iloc is indexing based locator through which we can access a particular set of values.

newdata.iloc[1,0]

'manas'