In [104]:
import pandas as pd

In [105]:
#             ======================== group-by and aggregation ==========================

In [106]:
data = pd.read_csv(r"/workspaces/ml/panda/sample_-_superstore (1).csv",encoding="latin-1")

In [107]:
data

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [108]:
new_data = data.groupby("Customer Name").agg(Total_Sales = ("Sales", "sum")).reset_index()

In [109]:
new_data

          Customer Name  Total_Sales
0         Aaron Bergman      886.156
1         Aaron Hawkins     1744.700
2        Aaron Smayling     3050.692
3       Adam Bellavance     7755.620
4             Adam Hart     3250.337
..                  ...          ...
788        Xylona Preis     2374.658
789       Yana Sorensen     6720.444
790      Yoseph Carroll     5454.350
791    Zuschuss Carroll     8025.707
792  Zuschuss Donatelli     1493.944

[793 rows x 2 columns]

In [110]:
# aggregate function ==> mean, max, min, count, sum 

new_data = data.groupby("Customer Name").agg(Total_Sales = ("Sales", "sum"), Avg_sal = ("Sales", "mean")).reset_index()
new_data

          Customer Name  Total_Sales     Avg_sal
0         Aaron Bergman      886.156  147.692667
1         Aaron Hawkins     1744.700  158.609091
2        Aaron Smayling     3050.692  305.069200
3       Adam Bellavance     7755.620  430.867778
4             Adam Hart     3250.337  162.516850
..                  ...          ...         ...
788        Xylona Preis     2374.658   84.809214
789       Yana Sorensen     6720.444  560.037000
790      Yoseph Carroll     5454.350  681.793750
791    Zuschuss Carroll     8025.707  258.893774
792  Zuschuss Donatelli     1493.944  165.993778

[793 rows x 3 columns]

In [111]:
customer_arriaval = data.groupby("Customer Name").agg(Arriaval = ("Customer Name", "count")).reset_index()
customer_arriaval

          Customer Name  Arriaval
0         Aaron Bergman         6
1         Aaron Hawkins        11
2        Aaron Smayling        10
3       Adam Bellavance        18
4             Adam Hart        20
..                  ...       ...
788        Xylona Preis        28
789       Yana Sorensen        12
790      Yoseph Carroll         8
791    Zuschuss Carroll        31
792  Zuschuss Donatelli         9

[793 rows x 2 columns]

In [112]:
#               ====================== sort =============================

In [113]:
customer_arriaval.sort_values("Arriaval", ascending= False)

           Customer Name  Arriaval
787        William Brown        37
387             John Lee        34
502         Matt Abelman        34
595           Paul Prost        34
145  Chloris Kastensmidt        32
..                   ...       ...
455         Lela Donovan         1
625      Ricardo Emerson         1
123         Carl Jackson         1
53     Anthony O'Donnell         1
378       Jocasta Rupert         1

[793 rows x 2 columns]

In [114]:
# ==================  merging two dataset  ============================

In [115]:
data1 = pd.read_csv(r"/workspaces/ml/panda/Product_ID,Product_Name,Profit_2014.csv")
data2 = pd.read_csv(r"/workspaces/ml/panda/Product_ID,Product_Name,Profit_2015.csv")

In [116]:
data1
data2
print(data1)
print("\n")
print(data2)

  Product_ID         Product_Name  Profit_2014
0       P001           Laptop Pro     120000.0
1       P002      Ergonomic Mouse      15000.0
2       P003           4K Monitor      65000.0
3       P004       Gaming Headset          NaN
4       P005            Webcam HD      10000.0
5       P006    Wireless Keyboard      20000.0
6       P007         External SSD      45000.0
7       P008            USB-C Hub       5000.0
8       P009       Privacy Filter          NaN
9       P010  Mechanical Keyboard      35000.0


  Product_ID              Product_Name  Profit_2015
0       P001                Laptop Pro     150000.0
1       P003                4K Monitor      75000.0
2       P004            Gaming Headset      30000.0
3       P006         Wireless Keyboard          NaN
4       P007              External SSD      45000.0
5       P008                 USB-C Hub       8000.0
6       P010       Mechanical Keyboard      40000.0
7       P011  Noise Cancelling Earbuds      25000.0
8       P012               Smart Watch          NaN
9       P013                VR Headset      60000.0

In [117]:
data1.isnull().sum()

Product_ID      0
Product_Name    0
Profit_2014     2
dtype: int64

In [118]:
#  ============   dropna method   ====================
#  for removing null values

In [119]:
data1 = data1.dropna()

In [120]:
data1

  Product_ID         Product_Name  Profit_2014
0       P001           Laptop Pro     120000.0
1       P002      Ergonomic Mouse      15000.0
2       P003           4K Monitor      65000.0
4       P005            Webcam HD      10000.0
5       P006    Wireless Keyboard      20000.0
6       P007         External SSD      45000.0
7       P008            USB-C Hub       5000.0
9       P010  Mechanical Keyboard      35000.0

In [121]:
mean_profit = data1["Profit_2014"].mean()

In [122]:
mean_profit

np.float64(39375.0)

In [123]:
data1 = data1.fillna(mean_profit)

In [124]:
data1

  Product_ID         Product_Name  Profit_2014
0       P001           Laptop Pro     120000.0
1       P002      Ergonomic Mouse      15000.0
2       P003           4K Monitor      65000.0
4       P005            Webcam HD      10000.0
5       P006    Wireless Keyboard      20000.0
6       P007         External SSD      45000.0
7       P008            USB-C Hub       5000.0
9       P010  Mechanical Keyboard      35000.0

In [125]:
data2.isnull().sum()

Product_ID      0
Product_Name    0
Profit_2015     2
dtype: int64

In [126]:
data2 = data2.fillna(data2["Profit_2015"].mean())

In [127]:
data2

  Product_ID              Product_Name  Profit_2015
0       P001                Laptop Pro     150000.0
1       P003                4K Monitor      75000.0
2       P004            Gaming Headset      30000.0
3       P006         Wireless Keyboard      54125.0
4       P007              External SSD      45000.0
5       P008                 USB-C Hub       8000.0
6       P010       Mechanical Keyboard      40000.0
7       P011  Noise Cancelling Earbuds      25000.0
8       P012               Smart Watch      54125.0
9       P013                VR Headset      60000.0

In [ ]:
datamerg = pd.merge(data1,data2, how="inner", on="Product_Name")

# inner
# left
# right
# outer

In [129]:
print(data1)
print("\n")
print(data2)
print("\n")
datamerg

  Product_ID         Product_Name  Profit_2014
0       P001           Laptop Pro     120000.0
1       P002      Ergonomic Mouse      15000.0
2       P003           4K Monitor      65000.0
4       P005            Webcam HD      10000.0
5       P006    Wireless Keyboard      20000.0
6       P007         External SSD      45000.0
7       P008            USB-C Hub       5000.0
9       P010  Mechanical Keyboard      35000.0


  Product_ID              Product_Name  Profit_2015
0       P001                Laptop Pro     150000.0
1       P003                4K Monitor      75000.0
2       P004            Gaming Headset      30000.0
3       P006         Wireless Keyboard      54125.0
4       P007              External SSD      45000.0
5       P008                 USB-C Hub       8000.0
6       P010       Mechanical Keyboard      40000.0
7       P011  Noise Cancelling Earbuds      25000.0
8       P012               Smart Watch      54125.0
9       P013                VR Headset      60000.0

  Product_ID_x         Product_Name  Profit_2014 Product_ID_y  Profit_2015
0         P001           Laptop Pro     120000.0         P001     150000.0
1         P003           4K Monitor      65000.0         P003      75000.0
2         P006    Wireless Keyboard      20000.0         P006      54125.0
3         P007         External SSD      45000.0         P007      45000.0
4         P008            USB-C Hub       5000.0         P008       8000.0
5         P010  Mechanical Keyboard      35000.0         P010      40000.0