In [3]:
import pandas as pd

In [4]:
data = pd.read_csv(r"/workspaces/ml/panda/sample_-_superstore (1).csv",encoding="latin-1")
data

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [5]:
# 1

orders = data[data["Profit"] > 0]
orders
states = orders.groupby("State")["Sales"].sum().sort_values(ascending=False).head(5)
states

State
California    415409.2655
New York      282163.2910
Washington    132841.3420
Michigan       75767.8040
Virginia       69868.9700
Name: Sales, dtype: float64

In [6]:
data

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [7]:
# 2

customer_profit = data.groupby("Customer Name")["Profit"].sum()
customer_profit
customer_orders = data.groupby("Customer Name")["Order ID"].count()
customer_orders

filtered_customer = customer_profit[customer_orders > 5]
filtered_customer.head(10)

Customer Name
Aaron Bergman          129.3465
Aaron Hawkins          365.2152
Aaron Smayling        -253.5746
Adam Bellavance       2054.5885
Adam Hart              281.1890
Adam Shillingsburg      64.5374
Adrian Barton         5444.8055
Adrian Hane             -2.3146
Aimee Bixby            313.6597
Alan Barnes            220.8130
Name: Profit, dtype: float64

In [8]:
# 3 

mean_dis = data.groupby("Category")["Discount"].mean()
mean_dis

avg_dis = mean_dis[mean_dis > 0.15]
avg_dis

Category
Furniture          0.173923
Office Supplies    0.157285
Name: Discount, dtype: float64

In [9]:
# 4 

region = data[data["Sales"] > 500].groupby("Region")["Quantity"].sum()
region
region = region.sort_values(ascending=False)
region

Region
West       1943
East       1738
Central    1280
South      1044
Name: Quantity, dtype: int64

In [10]:
# 5

high_avg = data[data["Category"] == "Technology"]
high_avg = high_avg.groupby("Sub-Category")["Sales"].mean().sort_values(ascending=False).head(3)
high_avg

Sub-Category
Copiers     2198.941618
Machines    1645.553313
Phones       371.211534
Name: Sales, dtype: float64

In [11]:
data

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [32]:
# 6

product_total = data.groupby("Product Name")["Profit"].sum()
product_total
product_quant = data.groupby("Product Name")["Quantity"].sum()
product_quant
filtered = product_total[product_quant > 10].sort_values(ascending=True)
filtered.head(5).reset_index()

                                        Product Name     Profit
0          Lexmark MX611dhe Monochrome Laser Printer -4589.9730
1  Chromcraft Bull-Nose Wood Oval Conference Tabl... -2876.1156
2  Bush Advantage Collection Racetrack Conference... -1934.3976
3          GBC DocuBind P400 Electric Binding System -1878.1662
4  Martin Yale Chadless Opener Electric Letter Op... -1299.1836

In [46]:
# 7

discount = data[data["Discount"] > 0.20]
discount
total = discount.groupby("Ship Mode")[["Sales", "Profit"]].sum()
total.sort_values(by="Profit", ascending=False).reset_index()

        Ship Mode        Sales      Profit
0        Same Day   22796.5750  -8306.6152
1     First Class   48150.9784 -19650.9894
2    Second Class   64272.0619 -20317.6731
3  Standard Class  227550.5345 -87100.7783

In [47]:
# 8

customer = data.groupby("Customer Name")[["Sales", "Profit"]].sum()
customer[customer["Sales"] > 10000]
customer.sort_values(by="Sales", ascending=False).reset_index()

       Customer Name      Sales     Profit
0        Sean Miller  25043.050 -1980.7393
1       Tamara Chand  19052.218  8981.3239
2       Raymond Buch  15117.339  6976.0959
3       Tom Ashbrook  14595.620  4703.7883
4      Adrian Barton  14473.571  5444.8055
..               ...        ...        ...
788       Roy Skaria     22.328     9.5838
789  Mitch Gastineau     16.739    -1.2453
790     Carl Jackson     16.520     1.6520
791     Lela Donovan      5.304     0.4641
792    Thais Sissman      4.833    -3.3156

[793 rows x 3 columns]

In [48]:
data

,Row ID,Order ID,Order_Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [75]:
# 9

top = data.groupby(["Region", "State"])["Sales"].sum()
top.sort_values(ascending=False)

Region   State
West     California              457687.6315
East     New York                310876.2710
Central  Texas                   170188.0458
West     Washington              138641.2700
East     Pennsylvania            116511.9140
South    Florida                  89473.7080
Central  Illinois                 80166.1010
East     Ohio                     78258.1360
Central  Michigan                 76269.6140
South    Virginia                 70636.7200
         North Carolina           55603.1640
Central  Indiana                  53555.3600
South    Georgia                  49095.8400
         Kentucky                 36591.7500
East     New Jersey               35764.3120
West     Arizona                  35282.0010
Central  Wisconsin                32114.6100
West     Colorado                 32108.1180
South    Tennessee                30661.8730
Central  Minnesota                29863.1500
East     Massachusetts            28634.4340
         Delaware                 27451.0690
         Maryland                 23705.5230
         Rhode Island             22627.9560
Central  Missouri                 22205.1500
         Oklahoma                 19683.3900
South    Alabama                  19510.6400
West     Oregon                   17431.1500
         Nevada                   16729.1020
East     Connecticut              13384.3570
South    Arkansas                 11678.1300
West     Utah                     11220.0560
South    Mississippi              10771.3400
         Louisiana                 9217.0300
East     Vermont                   8929.3700
South    South Carolina            8481.7100
Central  Nebraska                  7464.9300
East     New Hampshire             7292.5240
West     Montana                   5589.3520
         New Mexico                4783.5220
Central  Iowa                      4579.7600
West     Idaho                     4382.4860
Central  Kansas                    2914.3100
East     District of Columbia      2865.0200
West     Wyoming                   1603.1360
Central  South Dakota              1315.5600
East     Maine                     1270.5300
         West Virginia             1209.8240
Central  North Dakota               919.9100
Name: Sales, dtype: float64

In [88]:
# 10 

cust = data.groupby(["Customer Name", "Category"])["Sales"].sum().reset_index()
cust
result = cust.sort_values(by=["Category", "Sales"], ascending=[True,False])
result.reset_index()

      index    Customer Name    Category     Sales
0      1895      Seth Vernon   Furniture  8332.090
1      1043       Joe Elijah   Furniture  6920.136
2      1664     Peter Fuller   Furniture  6837.348
3       358  Caroline Jumper   Furniture  6267.194
4       862        Greg Tran   Furniture  6219.260
...     ...              ...         ...       ...
2177    652  Dorothy Badders  Technology     9.096
2178    633    Dianna Arnett  Technology     3.152
2179   1410    Maureen Gnade  Technology     2.376
2180    518     Dan Campbell  Technology     1.584
2181   1554     Neil Knudson  Technology     0.990

[2182 rows x 4 columns]